on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Create release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump Version
        uses: ./
        id: bump
        with:
          configuration: ".github/workflows/release_config.json"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v1
        id: changelog
        with:
          fromTag: "v${{ steps.bump.outputs.previous_version }}"
          configuration: ".github/workflows/release_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: "${{ steps.changelog.outputs.changelog }}"
          name: "v${{ steps.bump.outputs.next_version }}"
          tag_name: "v${{ steps.bump.outputs.next_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Bump PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "build(version): update version to ${{ steps.bump.outputs.next_version }}"
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>
          branch: build/bump-to-${{ steps.bump.outputs.next_version }}
          delete-branch: true
          base: main
          title: Bump version to ${{ steps.bump.outputs.next_version }}
          body: ""
          labels: "no changelog"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
