on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Create release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump Version
        uses: ./
        id: bump
        with:
          configuration: ".github/workflows/release_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Head
        id: head
        if: ${{ steps.bump.outputs.has_bump == 'true' }}
        run: echo "::set-output name=head::$(git rev-parse HEAD)"

      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v1
        id: changelog
        if: ${{ steps.bump.outputs.has_bump == 'true' }}
        with:
          configuration: ".github/workflows/release_config.json"
          fromTag: v${{ steps.bump.outputs.previous_version }}
          toTag: ${{ steps.head.outputs.head }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.bump.outputs.has_bump == 'true' }}
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          name: v${{ steps.bump.outputs.next_version }}
          tag_name: v${{ steps.bump.outputs.next_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Bump PR
        uses: peter-evans/create-pull-request@v3
        if: ${{ steps.bump.outputs.has_bump == 'true' }}
        with:
          commit-message: "build(version): update version to ${{ steps.bump.outputs.next_version }}"
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>
          branch: build/bump-to-${{ steps.bump.outputs.next_version }}
          delete-branch: true
          base: main
          title: Bump version to ${{ steps.bump.outputs.next_version }}
          body: ""
          labels: "no release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
